#pragma once

#ifndef GATEWARE_ENABLE_CORE
#define GATEWARE_ENABLE_CORE
#endif

#ifndef GATEWARE_ENABLE_SYSTEM
#define GATEWARE_ENABLE_SYSTEM
#endif

#ifndef GATEWARE_ENABLE_GRAPHICS
#define GATEWARE_ENABLE_GRAPHICS
#endif

#ifndef GATEWARE_ENABLE_MATH
#define GATEWARE_ENABLE_MATH
#endif

#ifndef GATEWARE_ENABLE_INPUT
#define GATEWARE_ENABLE_INPUT
#endif

#ifndef GATEWARE_DISABLE_GDIRECTX11SURFACE
#define GATEWARE_DISABLE_GDIRECTX11SURFACE
#endif

#ifndef GATEWARE_DISABLE_GDIRECTX12SURFACE
#define GATEWARE_DISABLE_GDIRECTX12SURFACE
#endif

#ifndef GATEWARE_DISABLE_GRASTERSURFACE
#define GATEWARE_DISABLE_GRASTERSURFACE
#endif

#ifndef GATEWARE_DISABLE_GOPENGLSURFACE
#define GATEWARE_DISABLE_GOPENGLSURFACE
#endif

#ifndef KHRONOS_STATIC
#define KHRONOS_STATIC
#endif

#include <vulkan/vulkan.h>
#include "Gateware.h"